// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Data.PostgreSql;

#nullable disable

namespace Data.PostgreSql.Migrations
{
    [DbContext(typeof(PostgreSeminarDbContext))]
    partial class PostgreSeminarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.Shop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("text")
                        .HasColumnName("a");

                    b.Property<long>("Created")
                        .HasColumnType("bigint")
                        .HasColumnName("c");

                    b.Property<long>("LastModified")
                        .HasColumnType("bigint")
                        .HasColumnName("lm");

                    b.Property<string>("Name")
                        .IsRequired()
                        .IsUnicode(true)
                        .HasColumnType("text")
                        .HasColumnName("n");

                    b.HasKey("Id");

                    b.ToTable("Shops", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
